version: '3'

services:
  nomad:
    image: inferrd/nomad
    command: agent -dev -data-dir=/tmp/nomad/data
    privileged: true
    networks: 
      - "inferrd"
    ports:
      - "4646:4646"
      - "4647:4647"
      - "4648:4648"
    environment:
      NOMAD_LOCAL_CONFIG: |
        bind_addr = "0.0.0.0"
        datacenter = "dc1"
        data_dir = "/tmp/nomad/data"
        client {
          min_dynamic_port = 20000
          max_dynamic_port = 20050
        }
        addresses {
          http = "0.0.0.0"
          rpc = "0.0.0.0"
          serf = "0.0.0.0"
        }
        advertise = {
          http = "${NOMAD_IP}"
          rpc = "${NOMAD_IP}"
          serf = "${NOMAD_IP}"
        }
        plugin "docker" {
          config {
          }
        }

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /tmp/nomad:/tmp/nomad:rw
      - /tmp:/tmp:rw
  
  db:
    image: postgres
    restart: always
    networks: 
      - "inferrd"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: inferrd
      POSTGRES_USER: inferrd
      POSTGRES_DB: inferrd

  redis:
    image: redis
    restart: always

  # # elastic:
  # #   image: elasticsearch:8.0.0
  # #   ports:
  # #     - "9200:9200"
  # #     - "9300:9300"
  # #   environment:
  # #     - "discovery.type=single-node"
  # #   restart: always

  # # fluent:
  # #   image: fluent/fluentd
  # #   command: sh ./local/entrypoint.sh
  # #   ports:
  # #     - "24224:24224"
  # #   restart: always
  # #   volumes:
  # #     - ./fluentd:/etc/fluent/

  api:
    image: inferrd/api
    networks: 
      - "inferrd"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - nomad
    environment:
      - DATABASE_URL=postgres://inferrd:inferrd@db:5432/inferrd
      - REDIS_URL=redis://redis:6379/0
      - NOMAD_SERVER=http://nomad:4646
      - DEBUG=inferrd/*
      - MACHINE_NETWORK_ROUTE=${MACHINE_NETWORK_ROUTE}
      - NODE_ENV=docker
      - APP_HOST=http://localhost:8080
      - API_HOST=http://localhost:3000
      - DOCKER_HOST=http://172.17.0.1:3000
      - LOGS_ES=https://elastic:9200
      - NOMAD_TOKEN=""

  ui:
    image: inferrd/ui
    networks: 
      - "inferrd"
    ports:
      - "8080:3001"
    depends_on:
      - api

networks:
  inferrd:
    name: inferrd
    driver: bridge